omod/src/main/webapp/pages/vitals/patient.gsp

@rkorytkowski I added an id to "confirm big right" button for UI test automation purposes

add id to ui button "confirm big right"

---

omod/src/main/resources/config.xml

https://issues.openmrs.org/browse/RA-940
modified:   omod/src/main/resources/config.xml

RA-940: Add Merge Patient app privilege via the Core Apps module

---

api/src/main/java/org/openmrs/module/coreapps/contextmodel/PersonContextModel.java

Added age so that it can be used in the formShowIf

RA-1065 - Added age to the context model

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
api/src/main/resources/messages.properties
omod/src/main/resources/apps/overallActions_extension.json
omod/src/main/resources/config.xml
omod/src/main/webapp/fragments/patientdashboard/visitIncludes.gsp
omod/src/main/webapp/pages/clinicianfacing/patient.gsp
omod/src/main/webapp/resources/scripts/custom/deletePatient.js

Added the *Delete Patient* entry and corresponding button in the general actions section

RA-1089: Implement a way to delete a patient in the ref app

---

api/src/main/java/org/openmrs/module/coreapps/contextmodel/PersonContextModel.java

So that it can be used as a test to display forms, also matches the REST webservice representation

RA-1166: Added deathdate to the person context model

---

omod/src/main/webapp/fragments/patientHeader.gsp

This PR is dependency for https://github.com/openmrs/openmrs-distro-referenceapplication/pull/164

RA-1208 - Applied more reliable component selection

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsProperties.java
api/src/main/resources/liquibase.xml
omod/src/main/resources/config.xml

Refer: https://talk.openmrs.org/t/page-reload-on-clicking-patient-header-data/8287

Fixed page redirection to incorrect Dashboard URL on clicking patient header data

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
api/src/main/java/org/openmrs/module/coreapps/CoreAppsProperties.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/patientdashboard/PatientDashboardPageController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/fragments/patientdashboard/visits.gsp
omod/src/main/webapp/pages/patientdashboard/patientDashboard.gsp
omod/src/main/webapp/resources/scripts/fragments/visitDetails.js
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentControllerTest.java

@dkayiwa Two commits actually implementing what's described in RA-1244.

RA-1244: Basic non-Ajax paging on the Patient Dashboard.

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
api/src/main/java/org/openmrs/module/coreapps/CoreAppsProperties.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/patientdashboard/PatientDashboardPageController.java
omod/src/main/webapp/resources/scripts/fragments/visitDetails.js
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentControllerTest.java

Same as 8cc5b59 (but without touching .travis.yml), this is reformatting ahead of the actual change implementing RA-1244.

RA-1244: Code reformatting.

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
api/src/main/java/org/openmrs/module/coreapps/customdatatype/CodedConceptDatatype.java
api/src/main/java/org/openmrs/module/coreapps/utils/VisitTypeHelper.java
api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/clinicianfacing/VisitsSectionFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/EditVisitFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/VisitIncludesFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientheader/ActiveVisitStatusFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/QuickVisitFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/ActiveVisitsPageController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/fragments/clinicianfacing/visitsSection.gsp
omod/src/main/webapp/fragments/patientdashboard/editVisit.gsp
omod/src/main/webapp/fragments/patientdashboard/visitDetailsTemplate.gsp
omod/src/main/webapp/fragments/patientdashboard/visitIncludes.gsp
omod/src/main/webapp/fragments/patientdashboard/visits.gsp
omod/src/main/webapp/fragments/patientheader/activeVisitStatus.gsp
omod/src/main/webapp/pages/activeVisits.gsp
omod/src/main/webapp/pages/clinicianfacing/patient.gsp
omod/src/main/webapp/pages/patientdashboard/patientDashboard.gsp
omod/src/main/webapp/resources/scripts/custom/visits.js
omod/src/main/webapp/resources/scripts/fragments/visitDetails.js
omod/src/main/webapp/resources/scripts/visit/filterTable.js
omod/src/main/webapp/resources/scripts/visit/jquery.dataTables.js
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/QuickVisitFragmentControllerTest.java

For testing purposes: Kindly enter the desired color codes and uuids for visit types under settings -> coreapps -> Visit Type colors.
Example: [{"uuid":"11f5b247-fd35-4688-8f0f-99748e84a9fd", "color":"red","shortName":"outpatient"},{"uuid":"f4540051-9212-4baf-8492-83f03b2f06b2", "color":"blue","shortName":"aids"},{"uuid":"b3322cf4-9e36-4a81-9dc8-c9c80731e06f","color":"green","shortName":"mch"}, {"uuid":"82508e7d-ab77-4ab6-81ec-a558ee97628f","color":"orange","shortName":"eyeclinic"}, {"uuid":"a16af3db-4f6d-4daf-b225-f57b48ed57af","color":"brown","shortName":"ante"}, {"uuid":"7b0f5697-27e3-40c4-8bae-f4049abfb4ed","color":"maroon","shortName":"facility"}]

RA-977: Option for user to select Visit Type on Start Visit on New UI

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientheader/ActiveVisitStatusFragmentController.java
omod/src/main/webapp/fragments/patientheader/activeVisitStatus.gsp

Backport 2 bug fixes from 'master' to '1.7.x' branch of Core Apps. Related to RA-1253
- https://github.com/openmrs/openmrs-module-coreapps/commit/66e0b4e29b34930cc653dda94b386391e04bb021
- https://github.com/openmrs/openmrs-module-coreapps/commit/9ddf408fbdc2cc4f2d70fb9b7287f3fd8da00cc2

RA-1253: Fix failing DeleteAllergyTest, AddNewAllergyTest and EditAllergyTest

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/EditProviderPageController.java
omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/pages/providermanagement/providerList.gsp

Thanks @mogoodrich  for reviewing these changes too. I just translated the strings and added the ability to capture the provider's address.

PROV-76, capture provider address and translate text

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/dashboardwidgets/DashboardWidgetFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/dashboardWidget.gsp

Added real config value to component

---

omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/visitbyencountertype/visitbyencountertype.controller.js
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/visitbyencountertype/visitbyencountertype.html

I did modify the link to open visit details page but it is not working so far. I did also modify the logic to show only one encounterType if more of the same type are present.

RA-1306 showing only one encounterType

---

omod/src/main/resources/apps/dashboardWidgets_app.json
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.component.js
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.controller.js
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.html

RA-1305 Relationships Widget

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/dashboardwidgets/DashboardWidgetFragmentController.java
omod/src/main/webapp/fragments/dashboardwidgets/dashboardWidget.gsp
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.controller.js
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.html

Hi @mogoodrich and @rkorytkowski, here are a few changes I made to the relationships widget in order to add patientPage config parameter. We will use this parameter to indicate where to navigate when selecting a person from the relationships list. I also added Integer patientId as another way to retrieve a patient in the DashboardWidgetFragmentController. 
Please let me know what you think. Thanks.

RA-1341, add patientPage config parameter

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
omod/src/main/compass/sass/patientHeader.scss
omod/src/main/resources/config.xml
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.controller.js
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.html

Hi @mogoodrich , here is the commit that implements relationships editing via the widget. It also contains a new privilege that gives user access to the edit function. Thanks.

RA-1342, implement edit and delete functions

---

omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.controller.js
omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/relationships/relationships.html

Hi @mogoodrich , thanks for identifying this bug with the person in a relationship that is not a patient.

RA-1342, fix bug when person in relationship is not patient

---

api/src/main/resources/messages.properties
omod/src/main/compass/sass/markpatientdead/markPatientDead.scss
omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java
omod/src/main/resources/apps/overallActions_extension.json
omod/src/main/webapp/pages/markPatientDead.gsp
omod/src/main/webapp/resources/scripts/custom/markPatientDead.js

This adds functionality  to mark patient dead. 
This is the reference for the PR https://issues.openmrs.org/browse/RA-134

Adding functionality to mark patient deceased.

---

omod/src/main/compass/sass/providermanagement/providermanagement.scss
omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/EditProviderPageController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/ProviderListPageController.java
omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/pages/providermanagement/providerList.gsp
omod/src/main/webapp/resources/scripts/providermanagement/editProvider.js
pom.xml

Hi @mogoodrich , here is the new UI for retiring a provider. Thanks.

PROV-77, add the ability to retire a provider

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/EditProviderPageController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/ProviderListPageController.java
omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/pages/providermanagement/providerList.gsp

Fix NPE bug. Thanks @mogoodrich .

PROV-77, fix NPE bug when un-retiring a retired provider

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/EditProviderPageController.java
omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/resources/scripts/providermanagement/editProvider.js

Thanks @mogoodrich . THis depends on the other providermanagement pr i just made.

PROV-78, display the list of supervisees on the supervisor's dashboard

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/EditProviderPageController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/ProviderListPageController.java
omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/pages/providermanagement/providerList.gsp

PROV-79, fix NPE bug in list CHW page

---

omod/src/main/compass/sass/stickynote/stickyNoteIcon.scss
omod/src/main/webapp/fragments/stickyNote.gsp
omod/src/main/webapp/resources/partials/clickToEditObs.html

PR to include the Sticky Note Font Awesome icon and adjust some of the styling.

RA-1287: Import Sticky Note Font Awesome icon

---

api/src/main/java/org/openmrs/module/coreapps/utils/VisitTypeHelper.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/ActiveVisitsPageController.java
omod/src/main/webapp/pages/activeVisits.gsp

Hi @mogoodrich  and @andrewmoko , I made some changes to this page and its controller to prevent crashing in our production servers. 
@andrewmoko : Do you have a test server that uses the multicolor multi visit type feature? Our PIH EMR and reference app QA servers only have one visit type. Just wanted to make sure I did not break any of the functionality you introduced with the multicolor visit types. Thanks!

RA-1381, improve the runtime of this page

---

omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/resources/scripts/providermanagement/editProvider.js

Fixing small bug with duplicate field ids.

PROV-78, fix small bug in the supervisor screen

---

omod/src/main/webapp/pages/providermanagement/editProvider.gsp
omod/src/main/webapp/resources/scripts/providermanagement/editProvider.js

PROV-81, add client side validation for duplicate identifiers

---

omod/src/main/webapp/fragments/stickyNote.gsp

Patch for the patient-name issue mentioned here: https://talk.openmrs.org/t/security-issues/12339

Patch xss in stickyNote

---

omod/src/main/webapp/pages/providermanagement/editProvider.gsp

Just fixing a bug with incorrect form field name.

PROV-84, saving CHW Health Facility

---

omod/src/main/webapp/fragments/clinicianfacing/diagnosisWidget.gsp

Fix XSS in [RA-1318](https://issues.openmrs.org/browse/RA-1318)

RA-1318 - Add html escaping in diagnosis section of patients.page 

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/QuickVisitFragmentController.java

https://issues.openmrs.org/browse/RA-1431

RA-1431: Prevent XSS in pop-up message after patient visit

---

api-2.2/pom.xml
omod/src/main/resources/config.xml
pom.xml

Create an api-2.2 sub module for the coreapps module.

TRUNK-5343: Create an api-2.2 sub module for the coreapps module.

---

api-pre2.2/pom.xml
omod/pom.xml
omod/src/main/resources/config.xml
pom.xml

This PR creates an api-pre2.2 sub module for the coreapps module.

TRUNK-5343: Create an api-pre2.2 sub module for the coreapps module.

---

api-pre2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java

The PR updates the license on the new EncounterDiagnosesElement for the new api-pre2.2 submodule

TRUNK-5343: Update license header for EncounterDiagnosesElement in api-pre2.2.

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/providermanagement/EditProviderPageController.java
omod/src/main/webapp/pages/providermanagement/editProvider.gsp

Add the ability to capture birthdate when registering a new CHW.

PROV-93, capture CHW birthdate

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientsearch/PatientSearchWidgetFragmentController.java
omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp
omod/src/main/webapp/resources/scripts/patientsearch/patientSearchWidget.js

Reverts openmrs/openmrs-module-coreapps#142

Revert "RA-1474: Coreapps: Patient Search Widget performed redundant search when running on OpenMRS 2.1.x"

---

api/src/main/java/org/openmrs/module/coreapps/parser/ParseEncounterToJson.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/patientdashboard/PatientDashboardPageController.java
omod/src/main/webapp/fragments/patientdashboard/visits.gsp
omod/src/main/webapp/resources/scripts/fragments/visitDetails.js
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentControllerTest.java

Restricting viewing and editing of Encounter data basing on the encounter type view and edit privileges
https://issues.openmrs.org/browse/RA-1485

RA-1485 Encounter Privileges Restriction Based on EncounterType Privileges

---

.gitignore
omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp

https://issues.openmrs.org/browse/RA-1518

RA-1518: Coreapps patientSearchWidget to bind selected id and name to search field than redirect

---

omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp

https://issues.openmrs.org/browse/RA-1534

RA-1534: Add an ID to the register patient button on the search widget for styling purposes

---

api/src/main/java/org/openmrs/module/coreapps/parser/ParseEncounterToJson.java

https://issues.openmrs.org/browse/RA-1555

RA-1555 Enable the use of configured date formats from the global property

---

omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp

Ticket : https://issues.openmrs.org/browse/AM-184

AM-184 : Fixed Impossible to create appointments(on demo server)

---

omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp

Reverts openmrs/openmrs-module-coreapps#167

Revert "AM-184 : Fixed Impossible to create appointments(on demo server)"

---

omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp

Ticket : https://issues.openmrs.org/browse/AM-184

AM-184 : Fixed Impossible to create appointments(on demo server

---

omod/src/main/webapp/fragments/mergepatients/patientSearchAndSelectWidget.gsp
omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp

https://issues.openmrs.org/browse/RA-1575

RA-1575: Set the minSearchCharacters to use the value of the minSearchCharacters global property

---

omod/src/main/java/org/openmrs/module/coreapps/web/resource/LatestObsResource.java

**Issue worked on**: https://issues.openmrs.org/browse/RA-1583
**Work done**: Updated resources needed to support platform 2.3.x for the coreapps module

RA-1583: Support openmrs platform 2.3.x

---

omod/pom.xml
omod/src/main/java/org/openmrs/module/coreapps/web/resource/LatestObsResource.java
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.spec.js
omod/src/test/java/org/openmrs/Allergen.java
omod/src/test/java/org/openmrs/AllergyReaction.java
omod/src/test/java/org/openmrs/module/coreapps/web/controller/LatestObsRestControllerTest.java
pom.xml

https://issues.openmrs.org/browse/RA-1520

RA-1520 Improve Performance of Latest Obs widget 

---

omod/src/main/webapp/pages/conditionlist/addCondition.gsp

Made changes in addCondition.gsp in order to support past dates
see https://issues.openmrs.org/browse/RA-1458
No? …

RA-1458: Onset date entry allows past dates

---

omod/src/main/webapp/pages/conditionlist/addCondition.gsp

Added labels next to condition and onset date fields in add new condition page
see https://issues.openmrs.org/browse/RA-1521
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …

RA-1521: Added labels to Condition and Onset Date fields

---

omod/src/main/webapp/pages/conditionlist/manageConditions.gsp

Renamed 'Cancel' to 'Return' in manage conditions UI
see https://issues.openmrs.org/browse/RA-1590
No? Unsure? -> …

RA-1590: Renamed Cancel button on Manage Conditions UI to Return

---

omod/src/main/webapp/pages/conditionlist/manageConditions.gsp

Renamed 'Active conditions' to 'Active' and 'Inactive conditions' to 'Inactive'
see https://issues.openmrs.org/browse/RA-1523
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …

RA-1523: Renamed Active and Inactive condition tabs

---

omod/src/main/webapp/pages/conditionlist/addCondition.gsp
omod/src/main/webapp/resources/scripts/conditionlist/controllers/addcondition.controller.js

Validation of end date in add conditions
see https://issues.openmrs.org/browse/RA-1597
No? Unsure? -> execute command …

RA-1597: End Date validation for conditions

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/conditionlist/AddConditionPageController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/pages/conditionlist/addCondition.gsp

changed addconditions.gsp
see https://issues.openmrs.org/browse/RA-1486
No? Unsure? -> execute command `git pull …

RA-1486: Conditions should be limited to diagnoses, findings, etc

---

api-2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java
api-pre2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java
api/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesByObsElement.java
api/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesByObsTagHandler.java
api/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesTagHandler.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/DiagnosesFragmentController.java
omod/src/main/webapp/fragments/diagnosis/encounterDiagnoses.gsp
omod/src/main/webapp/resources/scripts/diagnoses/diagnoses-angular.js
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/DiagnosesFragmentControllerTest.java
omod/src/test/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesTagHandlerComponentTest.java

Ticket : https://issues.openmrs.org/browse/RA-1610

RA-1610: <encounterDiagnoses*/> to specify a 'diagnosisConceptSources' attribute.

---

omod/src/main/webapp/resources/scripts/diagnoses/diagnoses-angular.js

Ticket : https://issues.openmrs.org/browse/RA-1610

RA-1610 : Follow up commit to fix 'diagnosisconceptsources' typo

---

.travis.yml
omod/src/main/webapp/pages/conditionlist/manageConditions.gsp

Removed plus and minus icons in manage conditions and replaced it with labels
see https://issues.openmrs.org/browse/RA-1616
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …

RA-1616: Replace plus minus icons with labels

---

omod/src/main/webapp/pages/conditionlist/manageConditions.gsp

changed hover message for 'x' icon in manage conditions 
see https://issues.openmrs.org/browse/RA-1613
No? Unsure? -> …

RA-1613:Change hover message for 'x' icon in manage conditions

---

omod/src/main/webapp/fragments/conditionlist/conditions.gsp

Fixed the bug while clicking 'x' icon on patient page.
Related PR: https://github.com/openmrs/openmrs-module-coreapps/pull/192
see https://issues.openmrs.org/browse/RA-1617
No? -> figure out why and add the fix to your commit. It …

RA-1617:Error on clicking 'x' on patient page.

---

omod/src/main/compass/sass/systemadministration/systemadministration.scss

This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
**Fix for for sys admin page css**
This PR will have more commit's when the project is going forward.
Ticket ID :- RA-1952

RA-1592 : Boostrap as a foundation for Reference Application UI Project.

---

omod/src/main/compass/sass/datamanagement/dataManagement.scss
omod/src/main/compass/sass/systemadministration/systemadministration.scss
omod/src/main/webapp/pages/datamanagement/dataManagement.gsp

This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1 Data management page css fix.
2 Sys admin page css fix.
This PR will have more commit's when the project is going forward.
Ticket ID :- RA-1952

RA-1592 : Boostrap as a foundation for Reference Application UI Project. 

---

omod/src/main/java/org/openmrs/module/coreapps/web/resource/LatestObsResource.java

**Issue worked on:** https://issues.openmrs.org/browse/RA-1626

RA-1626: Support openmrs platform 2.4.x

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/clinicianfacing/PatientPageController.java

Added new feature on the coreapps. Ticket (issue) no RA-1619(https://issues.openmrs.org/browse/RA-1619) Display forms for patients based on the program(s) enrolled

RA-1619 Display forms for patients based on the program(s) enrolled

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

Ticket: https://issues.openmrs.org/browse/RA-1551

RA-1551: Program Status widget enroll form should have sensible defaults

---

omod/src/main/resources/config.xml

Ticket: https://issues.openmrs.org/browse/RA-1645

RA-1645: 2.2.x-conditional submodule to support 2.2.0 and above.

---

omod/src/main/webapp/resources/scripts/conditionlist/controllers/editcondition.controller.js

fixed issue with end date while editing
see https://issues.openmrs.org/browse/RA-1628
No? Unsure? -> execute command …

RA-1628:Condition list -- deactivated conditions default end date is "undefined"

---

omod/src/main/compass/sass/patientsearch/patientSearchWidget.scss
omod/src/main/webapp/pages/datamanagement/dataManagement.gsp
omod/src/main/webapp/resources/partials/clickToEditObs.html
pom.xml

This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1 Data management page css fix.
2 Sys admin page css fix.
This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

RA-1592: Minor styling fixes + dependency on UICM 2.9.0-SNAPSHOT.

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentController.java
omod/src/main/webapp/fragments/patientdashboard/visitDetailsTemplate.gsp
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentControllerTest.java

Community Ticket: https://issues.openmrs.org/browse/RA-1648

RA-1648: Hide the 'Edit Visit' link for single visit type setups.

---

README.md

fixed some spelling errors in the file.

fix(docs): Update README.md - fix spelling

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

Ticket : https://issues.openmrs.org/browse/RA-1653

RA-1653: Program Status widgets, single call to location REST endpoint.

---

omod/src/main/webapp/pages/conditionlist/manageConditions.gsp

LINK:https://issues.openmrs.org/browse/RA-1641
Condition list--inactive conditions are not displayed

RA-1641:Condition list--inactive conditions are not displayed

---

omod/src/main/webapp/resources/scripts/conditionlist/controllers/editcondition.controller.js

link:https://issues.openmrs.org/browse/RA-1628
Condition list --deactivate conditions default end date is undefined

Condition list --deactivate conditions default end date is undefined

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js

Ticket: https://issues.openmrs.org/browse/RA-1680

RA-1680: Extra blank columns removed from 'obsacrossencounter' widget.

---

api-2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java
api-2.2/src/test/java/org/openmrs/module/htmlformentry/EncounterDiagnosesElementTest.java

Ticket: https://issues.openmrs.org/browse/RA-1694

RA-1694: EncounterDiagnosis to only display current encounter diagnoses.

---

omod/src/main/webapp/pages/clinicianfacing/patient.gsp

Ticket : https://issues.openmrs.org/browse/RA-1688

RA-1688 : Expand General Actions Column to remove word wrap of action titles

---

omod/src/main/webapp/pages/conditionlist/manageConditions.gsp
omod/src/main/webapp/resources/scripts/conditionlist/controllers/manageconditions.controller.js

link:https://issues.openmrs.org/browse/RA-1677

RA-1628:Condition List:Voiding/Deleting condition should delete entire history

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.html

https://issues.openmrs.org/browse/RA-1698

RA-1698: Fixed ObsAccrossEncounter table to be auto.

---

omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js

Ticket : https://issues.openmrs.org/browse/RA-1665

RA-1665: Follow-up commit for displaying numeric obs.

---

omod/src/main/webapp/fragments/stickyNote.gsp

Jira ticket: https://issues.openmrs.org/browse/RA-452

RA-452: Remove XSS vulnerabilities

---

omod/src/main/webapp/fragments/conditionlist/conditions.gsp

Fixed the issue of dialog box appearing behind other components...
https://issues.openmrs.org/browse/RA-1702

RA-1702:UI issue in deleting Condition from main patient dashboard

---

api-2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java

Ticket : https://issues.openmrs.org/browse/RA-1705

RA-1705: <encounterDiagnoses/> tag submission handling done in self CustomFormSubmissionAction

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/PatientHeaderFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/clinicianfacing/PatientPageController.java
omod/src/main/webapp/fragments/patientHeader.gsp
omod/src/main/webapp/pages/clinicianfacing/patient.gsp
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/PatientHeaderFragmentControllerTest.java
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/clinicianfacing/PatientPageControllerTest.java

Ticket : https://issues.openmrs.org/browse/RA-1643

RA-1643: Patient Header and bread crumbs to display all possible patient names and/or related info.

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.html

Ticket : https://issues.openmrs.org/browse/RA-1699

RA-1699: 'obsacrossencounters' widget table to be horizontally auto-scrollable.

---

omod/src/main/web/dashboardwidgets/programs/programs.controller.js
omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js
omod/src/main/web/dashboardwidgets/relationships/relationships.controller.js

@mogoodrich, @mseaton  , I just added some error handling when fetching the privileges. Hope this would provide more debug info when it fails next time.

RA-1709, check for errors when fetching user privileges

---

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js

Ticket : https://issues.openmrs.org/browse/RA-1724

RA-1724: Fix NPE/undefined error in obsgraph dashboard widget.

---

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js

- Added optional `encounterType` parameter to ObsGraph
Related Issue Card: https://issues.openmrs.org/browse/RA-1725
Related Talk Topic: https://talk.openmrs.org/t/adding-optional-encounter-type-parameter-to-obsgraph-widget/27327

RA-1725: ObsGraph - Added optional filter encounter type parameter for obsgraph

---

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js

Ticket : https://issues.openmrs.org/browse/RA-1724

RA-1724: Follow-on commit to fix nul typo

---

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js

- Add null data point when a concept does not have observations

RA-1727: Fix Obsgraph to show chart of correct concept to obs values.

---

api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/ActiveDrugOrdersFragmentController.java
omod/src/main/webapp/fragments/patientdashboard/activeDrugOrders.gsp
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/ActiveDrugOrdersFragmentControllerTest.java
omod/src/test/resources/dispensedMedication_app.json

Ticket : https://issues.openmrs.org/browse/RA-1729

RA-1729: Copying 'Dispensed Medication' widget from Order Entry UI.

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

Ticket: https://issues.openmrs.org/browse/RA-1737

RA-1737: <programstatus/> to maximise/minimise states based on param.

---

omod/src/main/web/dashboardwidgets/relationships/relationships.html

Ticket: https://issues.openmrs.org/browse/RA-1743

RA-1743: Relationship type names to L10n on Core Apps rel. widget.

---

omod/src/main/webapp/pages/systemadministration/systemAdministration.gsp

Related ticket:
https://issues.openmrs.org/browse/RA-1761

RA-1761: Hide content of System Administration page for user without appropriate privilege

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/ActiveDrugOrdersFragmentController.java
omod/src/main/webapp/fragments/patientdashboard/activeDrugOrders.gsp
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/ActiveDrugOrdersFragmentControllerTest.java
omod/src/test/resources/dispensedMedication_app.json

Ticket: https://issues.openmrs.org/browse/RA-1759

RA-1759: Dispensed Medication patient summary widget to have configurable 'returnUrl'

---

api-2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java
api-2.2/src/test/java/org/openmrs/module/htmlformentry/EncounterDiagnosesElementTest.java

Ticket: https://issues.openmrs.org/browse/RA-1760

RA-1760: Encounter diagnoses VIEW mode to follow 'preferredCodingSource'

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsActivator.java
api/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDispositionTagHandler.java
omod/src/test/java/org/openmrs/module/coreapps/htmlformentry/EncounterDispositionTagHandlerComponentTest.java
pom.xml

This PR modifies the `EncounterDispositionTagHandler` to support the new filtering based on `EncounterType` added [by this PR](https://github.com/openmrs/openmrs-module-emrapi/pull/184).
PS I expect Travis to fail on this as it depends on currently unreleased code.

RA-1770: Allow dispositions to be filtered based on EncounterType

---

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.html

Related issue - https://issues.openmrs.org/browse/RA-1768

RA-1768: Fixed overflow of column labels in obsgraph.

---

omod/src/main/webapp/pages/clinicianfacing/patient.gsp

This should conclude https://issues.openmrs.org/browse/RA-1764

Pt 2 of RA-1764  Clinician-Facing Dashboard: on small screen resolutions, visit actions should be at the top and general/other actions at the bottom

---

omod/src/main/webapp/fragments/conditionlist/conditions.gsp

Related ticket:
https://issues.openmrs.org/browse/RA-1746

RA-1746: Resolved issue with deleting the condition

---

omod/src/main/webapp/fragments/conditionlist/conditions.gsp

Related ticket:
https://issues.openmrs.org/browse/RA-1745

RA-1745: Resolved issue with conditions widget - show only active conditions

---

README.md
omod/src/main/compass/sass/patientsearch/patientSearchWidget.scss
omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp
omod/src/main/webapp/resources/scripts/patientsearch/patientSearchWidget.js

supports https://github.com/openmrs/openmrs-module-registrationapp/pull/81
https://pihemr.atlassian.net/browse/UHM-4635

Make patientSearchWidget responsive

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java

Ticket: https://issues.openmrs.org/browse/RA-1790

RA-1790 Modify MarkPatientDeadPageController to expect a uuid or integer

---

omod/src/main/java/org/openmrs/module/coreapps/web/resource/LatestObsResource.java
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.spec.js
omod/src/test/java/org/openmrs/module/coreapps/web/controller/LatestObsRestControllerTest.java

Ticket: https://issues.openmrs.org/browse/RA-1789

RA-1789: latestobsforconceptlist to take 'nLatestObs'.

---

omod/src/main/compass/sass/patientHeader.scss
omod/src/main/webapp/fragments/patientHeader.gsp
omod/src/main/webapp/fragments/patientdashboard/contactInfo.gsp
omod/src/main/webapp/fragments/patientdashboard/contactInfoInline.gsp

https://pihemr.atlassian.net/browse/UHM-4634

UHM-4634 Reformat patient header for better viewing on tablets

---

omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.html
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.spec.js

This includes some refactoring and code cleanup. I'll point out the functional changes.

For Latest Obs For Concept List, make concept name type configurable

---

omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js

Repeating https://github.com/openmrs/openmrs-module-coreapps/pull/339 . I accidentally overwrote those changes in https://github.com/openmrs/openmrs-module-coreapps/pull/337.

Fix obs datetime again (see 8682480)

---

api/src/main/java/org/openmrs/module/coreapps/htmlformentry/CodedOrFreeTextObsTagHandler.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/DiagnosesFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/PatientHeaderFragmentController.java

Issue I work on : https://issues.openmrs.org/browse/RA-1820

RA-1820 Unused local variables should be removed

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/clinicianfacing/PatientPageController.java

Using the ```equal(Object)``` to test equality between objects and strings.

RA-1834:Comparison of String objects using == or !=

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/VisitIncludesFragmentController.java

[RA-1827](https://issues.openmrs.org/browse/RA-1827):  Collapsible "if" statements should be merged.
Collapsible "if" statements, as described [here](https://issues.openmrs.org/browse/RA-1827), has been merged.
Please review and merge if all is ok.

RA-1827:  Collapsible "if" statements should be merged

---

omod/src/main/java/org/openmrs/module/coreapps/web/resource/LatestObsResource.java

[RA-1830](https://issues.openmrs.org/browse/RA-1830): Conditionally executed code should be reachable
Removed unreachable if statement. [Issue Description](https://issues.openmrs.org/browse/RA-1830)
I am opened for corrections

RA-1830: Conditionally executed code should be reachable

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientheader/ActiveVisitStatusFragmentController.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/ActiveVisitsPageController.java

[RA-1829](https://issues.openmrs.org/browse/RA-1829): Boolean expressions should not be gratuitous
Removed redundant if statement as [described](https://issues.openmrs.org/browse/RA-1829).

RA-1829: Boolean expressions should not be gratuitous

---

omod/src/main/web/dashboardwidgets/programs/programs.controller.js
omod/src/main/web/dashboardwidgets/programs/programs.html

https://issues.openmrs.org/browse/RA-1530

Make ctrl-click on a patient program link open in a new tab

---

omod/src/main/web/dashboardwidgets/programs/programs.controller.js
omod/src/main/web/dashboardwidgets/programs/programs.html

This fixes an issue introduced in 4546d08e7ac2bf85978b947c84822efc0e8f8cba
which causes the "Enroll" button not to work.
https://issues.openmrs.org/browse/RA-1530

RA-1530 Program List dashboard links don't behave like real links: take 2

---

omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js

https://issues.openmrs.org/browse/RA-1840

RA-1840 latestobsforconceptlist widget broken

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

https://issues.openmrs.org/browse/RA-1844

RA-1844:PatientDashboardWidgets: Program Widget improvements

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/DiagnosesFragmentController.java

Issue I work on : https://issues.openmrs.org/browse/RA-1826

RA-1826 Modifiers should be declared in the correct order

---

api/src/main/java/org/openmrs/module/coreapps/utils/VisitTypeHelper.java

Issue I work on : https://issues.openmrs.org/browse/RA-1825

RA-1825 Boolean checks should not be inverted

---

omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/patientdashboard/ActiveDrugOrdersFragmentControllerTest.java
omod/src/test/java/org/openmrs/module/coreapps/web/controller/LatestObsRestControllerTest.java

Issue I work on : https://issues.openmrs.org/browse/RA-1823

RA-1823 Assertion arguments should be passed in the correct order

---

api/src/main/java/org/openmrs/module/coreapps/utils/VisitTypeHelper.java

issue I work on : https://issues.openmrs.org/browse/RA-1822

RA-1822 Local variables should not be declared and then immediately returned

---

api/src/main/java/org/openmrs/module/coreapps/utils/VisitTypeHelper.java

Issue I work on : https://issues.openmrs.org/browse/RA-1824

RA-1824 Boolean literals should not be redundant

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/clinicianfacing/PatientPageController.java

issue I work on : https://issues.openmrs.org/browse/RA-1620

RA-1620 Ensure that form filling follows the correct order

---

omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js
omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js

https://issues.openmrs.org/browse/RA-1850

RA-1850 obsacrossencounters displays unwanted empty entries because of unrelated obsgroup

---

omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
omod/src/main/web/dashboardwidgets/visitbyencountertype/visitbyencountertype.html

https://issues.openmrs.org/browse/RA-1856
In the latestobsforconceptlist it was missing the "openmrsTranslate"
In the visitbyencountertype the message "none" was hard coded in the file.

RA-1856: latestobsforconceptlist to import openmrsTranslate.

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

Ticket ID:
https://issues.openmrs.org/browse/RA-1874
Problem:
Its possible to press the enroll button multiple times and as consequence, enroll the patient multiple times
Description:
Added variable requestInProgress to disable the Enroll Button while the request is being processed

RA-1874: Added variable tracking that Enroll button is clicked.

---

omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js
omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js

@mogoodrich , I have added two new config parameters to the obsgraph in order to satisfy the requirements for UHM-1676. 
I also included a small change @brandones asked regarding the maxAge parameter. Thanks!

RA-1887, add showLegend and hideConcepts config parameters

---

omod/src/main/webapp/resources/scripts/patientsearch/patientSearchWidget.js

Link to related ticket:
https://issues.openmrs.org/browse/RA-1740

RA-1740: Records on Patients list are doubled after using search field

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

Related ticket: 
https://issues.openmrs.org/browse/RA-1774

RA-1774: Patient program state timezone issues

---

omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js

Related ticket:
[https://issues.openmrs.org/browse/RA-1900](https://issues.openmrs.org/browse/RA-1900)

RA-1900 Function to count days from widgets start counting from 0 days

---

omod/pom.xml
omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.html
omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.spec.js
package.json

https://issues.openmrs.org/browse/RA-1899
This also improves some UI text in the latestobsforconceptlist widget.

RA-1899 pt 1: Write tests for latestobsforconceptlist

---

omod/src/main/web/dashboardwidgets/visitbyencountertype/visitbyencountertype.controller.js

https://issues.openmrs.org/browse/RA-1901
[visitbyencountertype](https://wiki.openmrs.org/display/docs/Patient+Summary+Widget+Documentation#PatientSummaryWidgetDocumentation-visitbyencounterRecentVisitbyEncounterType) widget to be configurable to show encounter dates (rather than visit date).

RA-1901: visitbyencountertype configurable to show encounter dates.

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js
omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.html
omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.spec.js
package.json

https://issues.openmrs.org/browse/RA-1899
Part one was here: https://github.com/openmrs/openmrs-module-coreapps/pull/385/
Hopefully these tests can serve as a template for tests for the other dashboardwidgets. I know visitbyencountertype is under active development, CC @mks-d .
The key to testing these is to make the controller concentrate all of its output in an `output` object, and make the HTML file as simple as possible (by concentrating logic in the controller). A bit of refactoring may be necessary to make the `$onInit` function of the controller return a promise that only resolves once the correct `output` has been produced. Tests then touch only three points: the widget config, the REST calls, and the output.
This also fixes a couple bugs with ObsAcrossEncounters.

RA-1899 Part 2 - Tests for obsacrossencounter patient summary widget

---

omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js
omod/src/main/web/dashboardwidgets/programs/programs.controller.js
omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

see https://issues.openmrs.org/browse/RA-1903

RA-1903: Check the role 'System Developer' to allow enrollment actions.

---

pom.xml

update uiframework version in coreapps  cc @dkayiwa

update uiframework version in coreapps

---

api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java
omod/src/main/webapp/pages/markPatientDead.gsp

This is dependent on EA-168, so it would be expected that tests don't pass until that is merged.

RA-1940: Reopen Closed Programs when a Patient is Marked as "Not Dead"

---

omod/src/main/web/dashboardwidgets/programstatus/programstatus.controller.js

https://issues.openmrs.org/browse/RA-1942

RA-1942 Redirect to Mark Patient Deceased page when program outcome changed *from* Patient Died

---

api/src/main/java/org/openmrs/module/coreapps/parser/ParseEncounterToJson.java
omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/RetrospectiveVisitFragmentController.java
omod/src/main/webapp/fragments/patientHeader.gsp
omod/src/main/webapp/fragments/patientdashboard/visitIncludes.gsp
omod/src/main/webapp/fragments/patientdashboard/visits.gsp
omod/src/main/webapp/pages/markPatientDead.gsp
omod/src/main/webapp/pages/mergeVisits.gsp
omod/src/main/webapp/resources/scripts/custom/utilsTimezone.js
omod/src/main/webapp/resources/scripts/custom/visits.js
omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/RetrospectiveVisitFragmentControllerTest.java

https://issues.openmrs.org/browse/RA-1905
Using the User propriety to save timezone.

RA-1905: Timezone support through clientTimezone user property.

---

omod/src/main/webapp/fragments/patientdashboard/encountertemplate/defaultEncounterTemplate.gsp

Ticket ID: [https://issues.openmrs.org/browse/RA-1873](https://issues.openmrs.org/browse/RA-1873)
Description:
Add access to viewEncounter on Visit Summary page for user that have view privilege on encounters

RA-1873: removed viewEncounter from If condition of editable privilege

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/diagnosis/EncounterDiagnosesFragmentController.java
omod/src/main/webapp/fragments/encounter/mostRecentEncounter.gsp
omod/src/main/webapp/fragments/htmlformentry/codedOrFreeTextAnswer.gsp
omod/src/main/webapp/fragments/mergepatients/patientSearchAndSelectWidget.gsp
omod/src/main/webapp/fragments/patientHeader.gsp
omod/src/main/webapp/fragments/patientdashboard/activeDrugOrders.gsp
omod/src/main/webapp/fragments/patientdashboard/visitDetailsTemplate.gsp
omod/src/main/webapp/fragments/patientsearch/patientSearchWidget.gsp
omod/src/main/webapp/pages/conditionlist/addCondition.gsp
omod/src/main/webapp/pages/conditionlist/editCondition.gsp
omod/src/main/webapp/pages/conditionlist/manageConditions.gsp
omod/src/main/webapp/pages/markPatientDead.gsp
omod/src/main/webapp/pages/mergeVisits.gsp
omod/src/main/webapp/pages/patientdashboard/patientDashboard.gsp
omod/src/main/webapp/pages/relationships/list.gsp
omod/src/main/webapp/pages/summarydashboard/summaryDashboard.gsp
omod/src/main/webapp/pages/vitals/patient.gsp

Hello @isears @sherrif10 
i have removed escapeJs method which is vulnerable to xss attacks.  However, i have left out the patient.gsp because changes were breaking the url referenced the links.
Thanks

RA-1424: Removed escapeJs which is vulnerable to xss

---

omod/src/main/webapp/fragments/htmlformentry/codedOrFreeTextAnswer.gsp
omod/src/main/webapp/pages/conditionlist/addCondition.gsp
omod/src/main/webapp/pages/conditionlist/editCondition.gsp

Hi Team,
@isears
Added angular sanitize from uicommons module to prevent XSS in 'directives/coded-or-free-text-answer.js'
Kindly refer to the following issue for more details:-
openmrs/openmrs-module-uicommons#88

Added angular sanitize  from uicommons for EMPT84

---

pom.xml

Bump emrapiVersion version from 1.32.0-SNAPSHOT to 1.32.0

Bump emrapiVersion to 1.32.0

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js

**Ticket:** [RA-1953](https://issues.openmrs.org/browse/RA-1953)
**Description:** Build table widget table data considering the original config obs ordering

RA-1953 - Ensure ObsAcrossEncounters column ordering respects configured obs order

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js

Just ordering the obs by encounter datetime in the descending order. 
https://issues.openmrs.org/browse/RA-1960

RA-1960, order obs by datetime descending

---

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js

Reverts openmrs/openmrs-module-coreapps#445

Revert "#RA-1983 - Refresh component after data is fetched"

---

app.json

Reverts openmrs/openmrs-module-coreapps#449

Revert "Use openmrs-module-coreapps module when setting up apps on PRs"

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java

@mogoodrich , is there anything else we need to do display this validation error? I just printed the error message:

UHM-7623, display error when failing to save patient

---

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDatesFragmentController.java
omod/src/main/webapp/fragments/patientdashboard/visits.gsp
omod/src/main/webapp/resources/scripts/custom/visits.js
omod/src/main/webapp/resources/scripts/fragments/visitDetails.js

Ticket: https://openmrs.atlassian.net/browse/RA-2034

RA-2034: Consider timezone when editing visit dates

---

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java
omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/pages/markPatientDead.gsp

see: https://openmrs.atlassian.net/jira/software/c/projects/RA/issues/RA-2035

RA-2035: Allow configuration of Minute Step when setting Deceased Date

---

omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java

Issue: https://openmrs.atlassian.net/browse/O3-2897

O3-2897: Add support for use of the concept name on  the global property `concept.causeOfDeath`

---

.gitignore
api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/coreapps/page/controller/summarydashboard/ProgramEnrollmentsPageController.java
omod/src/main/webapp/pages/summarydashboard/programEnrollments.gsp

@mogoodrich , I was able to include a table with the current program enrollment in this new page:
It was nice that the statistics numbers matched the number of the rows in this new table. :-)

SL-671: display the active program enrollmenets

---

omod/src/main/webapp/resources/scripts/patientsearch/patientSearchWidget.js

Please remove this PR. 
FYI: @mogoodrich , @mseaton

Add a loader when searching for a patient with fingerprints

---

omod/src/main/webapp/fragments/conditionlist/conditions.gsp
omod/src/main/webapp/pages/conditionlist/manageCondition.gsp
omod/src/main/webapp/pages/conditionlist/manageConditions.gsp
omod/src/main/webapp/resources/scripts/conditionlist/controllers/condition.controller.js
omod/src/main/webapp/resources/scripts/conditionlist/controllers/conditions.controller.js
omod/src/main/webapp/resources/scripts/conditionlist/restful-services/restful-service.js

@mseaton and @mogoodrich , I got this widget working again using the webservices REST condition end point. Here are some screenshots that show I have tested all the CRUD operations using this widget:

RA-2067: refactor widget to use webservices REST condition

---

omod/src/main/webapp/resources/scripts/patientsearch/patientSearchWidget.js

@mogoodrich , here is just a small fix that removes null objects from the search results that the patient REST could return.

UHM-8591: remove any potential null values from the search results
