omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/clinicianfacing/VisitsSectionFragmentController.java
The 'End Visit' issue on patient dashboard when navigating from the share/edit icon on the clinician facing resolved.
Also, the issue of missing patient id when also navigating from the clinician facing using the share/edit icon in coreapps v 1.10-SNAPSHOT was also resolved.
ticket: https://issues.openmrs.org/browse/RA-1002
**Below is snapshot of working version:**
- On patient clinician facing with active visit:
- Clicking on the share/edit icon from the clinician facing, and then clicking on end visit:
- After ending visit:
- Clicking on share/edit icon from patient clinician facing without active visit will give you this:
=> (RA-1002): Resolved 'end visit' issue  and missing patient id

omod/src/main/webapp/fragments/clinicianfacing/diagnosisWidget.gsp
This PR adds ID to diagnoses list component is helpful when extracting diagnoses list for testing purposes.
See https://github.com/openmrs/openmrs-distro-referenceapplication/pull/134 comments for details.
TLDR;
By @rkorytkowski 
> You are not allowed to use driver. Replace with List diagnoses = patientDashboardPage.getDiagnoses(); assertThat(diagnoses, contains(...));
getDiagnoses should locate diagnoses using css selector, xpath expression or by id
=> RA-1102 - Added ID to diagnoses list component

omod/src/main/compass/sass/patientHeader.scss, omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/PatientHeaderFragmentController.java, omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/patientheader/ActiveVisitStatusFragmentController.java, omod/src/main/resources/apps/patientHeader_extension.json, omod/src/main/webapp/fragments/patientHeader.gsp, omod/src/main/webapp/fragments/patientheader/activeVisitStatus.gsp
Create 2 extension points in the Patient Header for easier customization
Extract the current Active Visit status bar and include it using one of the new extension points instead ('secondLineFragment')
Details:
- Modify the Patient Header fragment controller to load the new extensions
- Add CSS declaration for the new extensions layout
- Move the Active Visit status bar style to an uppper level for extensions to use it
- Insert the Groovy code to load the extension points with appropriate config parameters
- Extract the current patient header's Active Visit status bar to an extension with its own controller
=> RA-1250: Add multiple extension points in the Patient Header

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/RetrospectiveVisitFragmentController.java, omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/RetrospectiveVisitFragmentControllerTest.java
Past visit visit have to end at 23.59.59.000 instead of 23.59.59.999 due to a bug in Hibernate 3.6.5-Final
modified:   omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/RetrospectiveVisitFragmentController.java
Modify Unit test to expect 23.59.59.000 instead of 23.59.59.999
modified:   omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/RetrospectiveVisitFragmentControllerTest.java
=> RA-1291: Set end date/time for past visits to 23.59.59.000

omod/src/main/resources/apps/dashboardWidgets_app.json, omod/src/main/webapp/resources/scripts/fragments/dashboardWidgetsCommons.service.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/obsacrossencounters/obsacrossencounters.component.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/visitbyencountertype/visitbyencountertype.component.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/visitbyencountertype/visitbyencountertype.controller.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/visitbyencountertype/visitbyencountertype.html
I wasn't sure what to do if there were no encounterTypes for a visit. See below for my solution. Second thing is that for now clicking the visit date redirects you only to all patient visits not specific one. To make this we need to provide visit and patient id which cannot be done via REST (?) so we would have to modify fragment controller ?
Screen shot
=> RA-1306 Visits By Encounter Type Widget

omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/dataintegrityviolations/dataintegrityviolations.component.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/dataintegrityviolations/dataintegrityviolations.controller.js, omod/src/main/webapp/resources/scripts/fragments/dashboardwidgets/dataintegrityviolations/dataintegrityviolations.html
I've used mocked response from future `dataintegrity` REST endpoint to create layout.
Ticket will be ready when endpoint is ready and this app's code is tweaked a bit to fit real-life response.
Note: Bold `Fix` labels got their `actionUrl` defined, so it means that they are clickable.
@rkorytkowski @ssmusoke Do you think that way of distinguishing clickable and non-clickable `Fix`es is OK?
=> RA-1304 - Data Integrity Violations Widget

omod/src/main/webapp/fragments/patientdashboard/visits.gsp
at org.apache.commons.lang.time.DateUtils.add(DateUtils.java:414) when
we have two active visits as a result of a failure to end the current
visit before starting a new one hence leading to stopDatetime being null
=> Fixing java.lang.IllegalArgumentException: The date must not be null

omod/src/main/resources/apps/dashboardWidgets_app.json
Hi @rkorytkowski , here is the config setting that would enable the editing in the reference app. That should help us to debug those errors we see with the new organization of the dashboard widgets. Thanks.
=> RA-1342, enable relationships editing in referenceapp

omod/src/main/compass/sass/clinicianfacing/patient.scss
... to the container size. Otherwise, the clear:left; fits the background to the text size. Calculated at width: 97.91666%; because the container has a 1.04167% margin on each side.
=> RA-1364 Adding width so the background stretches..

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/diagnosis/EncounterDiagnosesFragmentController.java
The PR fixes JSON parse error when existingObs is null. This happens after a visit note was previously saved with a diagnosis.
=> TRUNK-5343: Fix JSON parse error when existingObs is null.

api-2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java, omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/diagnosis/EncounterDiagnosesFragmentController.java, omod/src/main/webapp/resources/scripts/diagnoses/diagnoses.js, omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/diagnosis/EncounterDiagnosesFragmentControllerTest.java, omod/src/test/webapp/resources/scripts/diagnoses/diagnoses.js
The PR fixes duplicating diagnoses when saving a visit note and implements deleting of diagnoses on a visit note.
=> Fix duplicating diagnoses when saving a visit note and implements deleting of diagnoses on a visit note.

api-2.2/src/main/java/org/openmrs/module/coreapps/htmlformentry/EncounterDiagnosesElement.java
The PR fixes the failure to delete an existing diagnosis when adding a new visit note.
=> TRUNK-5343: Fix the failure to delete an existing diagnosis when adding a new visit note

omod/src/main/webapp/pages/providermanagement/editProvider.gsp, omod/src/main/webapp/resources/scripts/providermanagement/editProvider.js
We added the ability to remove a supervisor from the supervisee screen. We added a remove button right beside the edit button that opens a dialog to confirm the removal of the supervisor. We are using the unassignSupervisee fragment with the supervisorID superviseeID.
Issue we worked on
https://issues.openmrs.org/browse/PROV-88
=> Adding the ability to remove a supervisor.

omod/src/main/webapp/pages/conditionlist/manageConditions.gsp, omod/src/main/webapp/resources/scripts/conditionlist/controllers/manageconditions.controller.js
Confirm if a condition has to be deleted before the action is performed
see https://issues.openmrs.org/browse/RA-1604 …
=> RA-1604: Confirmation before deleting a condition

.travis.yml, omod/src/main/webapp/pages/conditionlist/addCondition.gsp
Changed UI for add conditions
see https://issues.openmrs.org/browse/RA-1609
No? Unsure? -> execute command `git pull …
=> RA-1609:Add condition UI enhancement

.travis.yml, omod/src/main/java/org/openmrs/module/coreapps/page/controller/conditionlist/EditConditionPageController.java, omod/src/main/webapp/pages/conditionlist/editCondition.gsp, omod/src/main/webapp/pages/conditionlist/manageConditions.gsp, omod/src/main/webapp/resources/scripts/conditionlist/controllers/editcondition.controller.js, omod/src/main/webapp/resources/scripts/conditionlist/controllers/manageconditions.controller.js
Added the functionality to edit an existing condition.
Related PR: https://github.com/openmrs/openmrs-module-emrapi/pull/168
see https://issues.openmrs.org/browse/RA-1526
No? -> figure out why and add the fix to your commit. It …
=> RA 1526- Editing conditions 

omod/src/main/web/dashboardwidgets/visitbyencountertype/index.js, omod/src/main/web/dashboardwidgets/visitbyencountertype/visitbyencountertype.controller.js, omod/src/main/web/dashboardwidgets/visitbyencountertype/visitbyencountertype.html
RA-1623:Encounter type name localisation in recent visit
Translate the encounter type name based on the locale in recent visit section of patient dashboard (coreapps).You need to store encounter type name in the form of key and their value in messages.properties.
Files which are modified are:
openmrs-module-coreapps/omod/src/main/web/dashboardwidgets/visitbyencountertype/visitbyencountertype.html
openmrs-module-coreapps/omod/src/main/web/dashboardwidgets/visitbyencountertype/visitbyencountertype.controller.js
openmrs-module-coreapps/omod/src/main/web/dashboardwidgets/visitbyencountertype/index.js
=> RA-1623:Encounter type name localisation

omod/src/main/webapp/fragments/dashboardwidgets/customLinksWidget.gsp
Translating link titles in custom links widget.
[Link to card](https://issues.openmrs.org/browse/RA-1640)
=> RA-1640: Localizing link titles in custom links widget.

omod/src/main/webapp/pages/clinicianfacing/patient.gsp
Ticket :https://issues.openmrs.org/browse/RA-1697
Improve "Actions" Column styling on the Patient DashBord
=> RA-1697: Improve Actions Column styling on the Patient DashBord

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js
Hi @mogoodrich , here is an updated PR for displaying concept SHORT names if configured via **_useConceptShortName_** widget config property. By default, it will continue to display the obs.value.display property. Thanks.
=> RA-1703, if specified via config property display concept short name

omod/src/main/webapp/resources/scripts/custom/visits.js, omod/src/main/webapp/resources/scripts/fragments/patientdashboard/encountertemplate/defaultEncounterTemplate.js, omod/src/main/webapp/resources/scripts/fragments/visitDetails.js
Made the change because in JQuery 3.4.1 the ajax successful call back is done() after deprecation of success() and fail() with deprecation of error() as the error call back function
https://issues.openmrs.org/browse/RA-1696
=> RA-1696:Switch from 'success()' to 'done()' and 'error()' to 'fail()' in JQuery 3.4.1

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.html
@mogoodrich , I think this is for the obscrossacounters widget to display retired concepts as grayed-out similar to the htmlform autocomplete widget. Thanks for reviewing it.
=> HTML-718, gray out retired concepts

omod/src/main/webapp/resources/scripts/fragments/patientdashboard/encountertemplate/defaultEncounterTemplate.js
JIRA: https://issues.openmrs.org/browse/RA-1622
When using a non-htmlformentry form, the patient dashboard generates "viewEncounter" and "editEncounter" links using the extension configuration to store the URL in the data-view-url or data-edit-url form as appropriate. Unfortunately, the click handler in defaultEncounterTemplate.js only handles a url stored in the data-edit-url form, resulting in an error when the view link is clicked.
=> RA-1622: Respect the value of data-view-url where available

omod/src/main/webapp/fragments/patientdashboard/encountertemplate/defaultEncounterTemplate.gsp, omod/src/main/webapp/resources/scripts/fragments/patientdashboard/encountertemplate/defaultEncounterTemplate.js
Added support to read editStyle from Fragment Configuration to make switch between edit styles(currently Standard and Simple). This will be used in handling edit and view button in **defaultEncounterTemplate** and edit button in View mode by passing the editStyle as a query parameter in **viewEncounterWithHtmlForm** controller
see https://issues.openmrs.org/browse/RA-1762
No? -> …
=> RA-1762: 'editStyle' config support for defaultEncounterTemplate.

omod/src/main/webapp/pages/vitals/patient.gsp
Replacing escapeJS filtering with more robust encodeJavaScript.
Original bug reported by Sarah Elder: https://talk.openmrs.org/t/openmrs-vulnerability-research-questions-and-report/27983
=> RA-1771: Fix xss in vitals page

omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
It's an arbitrary and undocumented limitation on implementers. Instead of having this limitation, a note should be added to the [wiki documentation](https://wiki.openmrs.org/display/docs/Patient+Summary+Widget+Documentation#PatientSummaryWidgetDocumentation-conceptlistLatestObsForConceptList) which advises implementers that adding too many concepts can impact performance.
=> Remove concept list size limit

omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js
Fixes an error introduced in https://github.com/openmrs/openmrs-module-coreapps/pull/336/files . I changed from `full` obs rep to a custom rep, but neglected to include `obsDatetime` in that rep.
=> Fix obs datetime

omod/src/main/web/dashboardwidgets/dashboardwidgetscommons.service.js, omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.controller.js, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.html
PIH ticket https://pihemr.atlassian.net/browse/UHM-4499
This includes very little functional change. I will indicate it in the comments.
Definitely use "hide whitespace changes" when reviewing.
It should be noted that although the [Documentation](https://wiki.openmrs.org/display/docs/Patient+Summary+Widget+Documentation#PatientSummaryWidgetDocumentation-conceptencountersObsAcrossEncounters) claims that `concepts` can be specified by ID, UUID, FSN, or Map, it's clear from the code that only UUID could possibly have worked. I haven't attempted to fix that in this PR.
=> Refactor obsacrossencounters controller; add useConceptNameForValue config option

api/src/main/java/org/openmrs/module/coreapps/parser/ParseEncounterToJson.java
[RA-1828](https://issues.openmrs.org/browse/RA-1828): Return of boolean expressions should not be wrapped into an "if-then-else" statement
Replaced if-then-else statement with a boolean expression. [Issue description](https://issues.openmrs.org/browse/RA-1828).
Please review and merge if all is ok.
=> RA-1828: Return of boolean expressions should not be wrapped into an "if-then-else" statement

README.md, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js
https://issues.openmrs.org/browse/RA-1800
Fixes a typo which caused ObsAcrossEncounter not to work
@sherrif10 I was unable to test that this actually fixes the problem, because I can't make any sense of "Manage Apps" and the widget "config"s. Please try testing using this branch and let me know if it fixes the problem. Sorry for the inconvenience.
=> RA-1800 Obs Across Encounter widget broken

omod/src/main/resources/apps/dashboardWidgets_app.json
The JIRA ticket describes an error because of which the "Health Trend Summary" is missing in the patient dashboard of Refapp 2.11.0. The pull request is to merge one commit to fix the ticket RA-1871 described at the below link:
https://issues.openmrs.org/browse/RA-1871
=> RA-1871: Fix for the missing Health Trend Summary in 2.11 patient dashboard

omod/src/main/webapp/fragments/patientdashboard/visitIncludes.gsp
Added the `ui.encodeHtmlContent()` to `ui.format(type)` in `visitIncludes.gsp` in order to prevent XSS.
https://issues.openmrs.org/browse/RA-1865
When adding a new visit type, one could submit `<script>alert("xss")</script>` as the type name. Then, upon navigating to the patient page for any patient, this script would be loaded and ran.
Malicious visit type name.
Script executed on patient page.
No script executed, visit type is shown properly escaped.
1. Login to OpenMRS as admin.
2. If you have no patients created, create a patient with any information.
3. Select "Configure Metadata"
4. Select "Add New Visit Type"
5. Create a new visit type with name `<script>alert("xss")</script>` and description `test`
6. From the main page, select "Find Patient Record"
7. Click on the row for any …
=> EMPT-78: Fixed XSS Vulnerability in Visit Type

omod/src/main/webapp/fragments/patientheader/activeVisitStatus.gsp
Added enocdeHtmlContent to the active visit location
Sanitized the active visit status for when you a patient is checked into a location when the name of the location is a script. The script would be executed when the patient is put into the location. The script will not be executed with this patch.
1. Launch OpenMRS application using the URL: http://localhost:8080/openmrs
2. Provide following info and click login​Username​ as ​admin​ Password​ ​ as ​admin123 Location as ​Inpatient
3. Click on the “System Administration” module.
4. Click on the “Advance Administration module.
5. Click on “Manage Locations” and then “Add Location”.
6. Enter <iframe src=’http://ncsu.edu’> as the Name and select all the Tags.
7. Hit Save Location.
8. Click on Home.
9. Click on “Find a Patient” module.
10. …
=> RA-1875: EMPT 52 Fixed XSS vulnerability in coreapps active visit status

omod/src/main/webapp/resources/scripts/patientsearch/patientSearchWidget.js
Encoded name of the patients in patient search results in patientSearchWidget.js file to prevent XSS.
Whenever a patient was created with an iframe or a script as name, the iframe/script would be executed whenever that patient's name would be searched on 'Find Patient' page.
There are two ways to replicate this vulnerability:
- Method 1
1. Launch the OpenMRS application.
2. Login with username "Admin" and password "Admin123" with location as Inpatient Ward.
3. Navigate to 'Register a Patient'.
4. Enter dummy details in required fields as `Given Name: <iframe src=”https://ncsu.edu”/>, Family Name: Family, Gender: Male, Birthdate: 1 January 2000, Address: 123 road` and click 'Confirm' at the end.
5. After getting redirected to the new patient’s dashboard, go to homepage and navigate to …
=> RA-1875: EMPT92 EMPT 96 Fixed XSS Vulnerability in Find Patient

omod/pom.xml, omod/src/main/resources/apps/dashboardWidgets_app.json, omod/src/main/web/dashboardwidgets/latestobsforconceptlist/latestobsforconceptlist.spec.js, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js
This addresses three problems identified in [RA-1899](https://issues.openmrs.org/browse/RA-1899):
- When Maven would run the tests, test failures would not cause the build to fail. This was fixed by upgrading the maven plugin.
- The tests are broken. This was fixed by reverting https://github.com/openmrs/openmrs-module-coreapps/pull/387 . More info on the reasoning for that is in [a comment there](https://github.com/openmrs/openmrs-module-coreapps/pull/387#issuecomment-828613239).
- There was a minor error in another test, unrelated to the above. The mock data was fixed.
The reverted commit was attempting to fix https://issues.openmrs.org/browse/RA-1864 and https://issues.openmrs.org/browse/RA-1871 . Those tickets will need re-testing.
=> RA-1899: Fix broken tests

omod/src/main/java/org/openmrs/module/coreapps/page/controller/systemadministration/SystemAdministrationPageController.java, omod/src/main/webapp/fragments/patientheader/activeVisitStatus.gsp
I check to see if the user doesn't have the privilege and isn't a superuser. If both of these are true then I throw an APIAuthenticationException
an issue where users without the coreapps.systemAdministration privilege are still able to access the system admin page at /openmrs/coreapps/systemadministration/systemAdministration.page
-Launch OpenMRS application using the URL: http://localhost:8080/openmrs
--
-Provide following info and click login​Username​ as ​admin​ Password​ ​ as ​admin123 Location as ​Inpatient
-Click on “System Administration”.
-Click on “Manage Accounts”.
-Click on the “Add New Account” button.
-In the “Family Name” field, type in “Megan”.
-In the “Given Name” field, type in “Jones”.
-Select Female as Gender.
-Check the “Add User Account?” checkbox.
-In “Username” …
=> RA-1875: EMPT32 in systemAdministrationPageControllor.java

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.html, omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.spec.js
**Ticket:** [RA-1916](https://issues.openmrs.org/browse/RA-1916)
**Description:**
- Answer obs are treated now as an array so that multiple answers can be presented for a concept within a widget cell
- On the html, when rendering the widget row, if an array is stored for the cell, all elements will be shown separated by a comma
- All elements on the obs array have their own associated css class, allowing to maintain the previous behavior of showing as grayed the voided concepts
- Questions with only one answer are shown as before, maintaining previous behaviour
cc @mks-d @dkayiwa
=> RA-1916: Coalesce multiple answers recorded for the same question on ObsAcrossEncounters widget.

omod/src/main/java/org/openmrs/module/coreapps/page/controller/MergeVisitsPageController.java, omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/MergeVisitsPageControllerTest.java, omod/src/test/java/org/openmrs/module/coreapps/page/controller/MergeVisitsPageControllerTest.java
https://issues.openmrs.org/browse/RA-1926
Merge Visits: Remove visitId from URL to prevent NPE if that visit was merged
=> RA-1926: Merge Visits: Remove visitId from URL to prevent NPE if that visit was merged

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/ParserEncounterIntoSimpleObjects.java, omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDetailsFragmentController.java, omod/src/main/webapp/fragments/patientdashboard/encountertemplate/defaultEncounterTemplate.gsp, omod/src/test/java/org/openmrs/module/coreapps/fragment/controller/visit/ParserEncounterIntoSimpleObjectsTest.java
**Ticket:**
https://issues.openmrs.org/browse/RA-1945
**What I have done:**
When ParserEncounterIntoSimpleObjects if we are dealing with an concept that is `numeric` we will cast to `conceptNumeric`
=> RA-1945: ParserEncounterIntoSimpleObjects to cast concepts to ConceptNumeric where applicable.

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java, omod/src/main/java/org/openmrs/module/coreapps/filter/AdminAuthorisationFilter.java, omod/src/main/resources/config.xml
A user without the privilege could access the administration page and all other functionalities.
I have just created a Filter to redirect every user, without the above privilege, to the home page.
cc @isears @dkayiwa @ibacher @sherrif10
=> MM-893: Solved Authentication Bypass to System Administration

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java, omod/src/main/java/org/openmrs/module/coreapps/page/controller/MarkPatientDeadPageController.java, omod/src/main/resources/config.xml, omod/src/main/webapp/pages/markPatientDead.gsp
Issue: https://issues.openmrs.org/browse/RA-1954
Create a global property `DECEASED_DATE_USING_TIME` that allows choosing if we want the Decease Date datepicker to have a time component.
If it's true we can select date + time.
If it's not true, we can only select date.
=> RA-1954 - Add GP DECEASED_DATE_USING_TIME 

pom.xml
UIFR-220 - Bump UiFrameworkVersion version to 3.22.0 to be able to use a new method from UiFramework
=> UIFR-220 - Bump UiFrameworkVersion version to 3.22.0 to be able to use a new method

api/src/main/java/org/openmrs/module/coreapps/contextmodel/PatientEncounterContextModel.java, omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/clinicianfacing/VisitsSectionFragmentController.java, omod/src/main/java/org/openmrs/module/coreapps/page/controller/clinicianfacing/PatientPageController.java, omod/src/main/java/org/openmrs/module/coreapps/page/controller/patientdashboard/PatientDashboardPageController.java
https://issues.openmrs.org/browse/RA-1968
This allows extension `require`s to refer to a patient's historical encounters. Demonstrated here with "Covid 19 Note d'Admission"
=> RA-1968: Add all patient encounters to context model

omod/src/main/web/dashboardwidgets/obsacrossencounters/obsacrossencounters.controller.js
The issue (https://issues.openmrs.org/browse/RA-1983):
ObsAcrossEncounters widgets might not show information or show only a small fraction
How to replicate:
1) Go to a page containing multiple ObsAcrossEncounters widgets (These should contain information)
2) Go into the browser dev tools -> Network tab -> make sure "Disable cache" is unchecked 
3) Refresh the page
Solution:
Add scope to component 
And refresh scope after all data has been fetched
=> #RA-1983 - Refresh component after data is fetched

app.json
When setting up apps on PRs, app.json file should use openmrs-module-coreapps not openmrs-contrib-qaframework.
=> Use openmrs-module-coreapps module when setting up apps on PRs

api/src/main/java/org/openmrs/module/coreapps/CoreAppsConstants.java, omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/visit/VisitDatesFragmentController.java, omod/src/main/java/org/openmrs/module/coreapps/page/controller/patientdashboard/PatientDashboardPageController.java, omod/src/main/resources/config.xml, omod/src/main/webapp/fragments/patientdashboard/editVisitDatesDialog.gsp, omod/src/main/webapp/fragments/patientdashboard/visits.gsp
Issue: https://issues.openmrs.org/browse/RA-1985
If a user creates a visit, and later on decide to edit said visit.
Currently its no possible to change time.  
The proposal is allowing the visit time to be changed
(According with the needs of the implementation)
Solution found: 
Adding global property to enable / disable useTime in the dateTimePicker
=> RA-1985 - Allow changing visit time dynamically

api/src/main/java/org/openmrs/module/coreapps/CoreAppsActivator.java
[RA-1831](https://issues.openmrs.org/browse/RA-1831): "@Override" should be used on overriding and implementing methods
Added @Override annotation to inherited methods. [Issue description](https://issues.openmrs.org/browse/RA-1831)
Please review and comment where necessary.
=> RA-1831: "@Override" should be used on overriding and implementing methods

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/dashboardwidgets/DashboardWidgetFragmentController.java
[[RA - 1833] - "toString() should never be called on a string object"](https://issues.openmrs.org/browse/RA-1833) 
Used the built-in find tool in IntelliJ to find `toString()` method calls, and looked for redundant usages and replaced the found one with just the original string.
=> RA-1833 Remove redudant toString() method calls

omod/src/main/webapp/pages/conditionlist/manageCondition.gsp, omod/src/main/webapp/pages/conditionlist/manageConditions.gsp, omod/src/main/webapp/resources/scripts/conditionlist/common.functions.js, omod/src/main/webapp/resources/scripts/conditionlist/controllers/condition.controller.js, omod/src/main/webapp/resources/scripts/conditionlist/controllers/conditions.controller.js
This PR addresses a number of issues with the Condition List date fields:
Reported issues fixed:
* It fixes RA-1678 such that dates submitted to the server are stored consistently with how they are entered on the client.
* It fixes RA-2012 by enabling the onset and end date input fields to be cleared/unset
Unreported issues fixed:
* Fixes syntax errors in JS causing Jasmine tests to fail
* Fixes bug that prevents marking conditions as inactive if the locale is anything other than English
* Fixes the display of onset and end dates in the condition list table to match refapp localized date formatting.
=> RA-1678 Condition List: Problems with time zones

omod/src/main/web/dashboardwidgets/programs/programs.html
Truncates the program name with ellipses (...) if the program name exceeds 20 characters (adding the full program name as a tooltip to view on hover), to ensure that it does not overflow into the dates.
Example:
=> Program display should not overflow into date display.

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/encounter/MostRecentEncounterFragmentController.java
@mogoodrich , this proved to be a bit more complicated than just searching for multiple encounter types. Each encounter type could have a different HTML form. So, I had to add configuration that maps encounterTypeUuid --> formName.
Here is how this new config node would look like:
encounterTypes : {
"55a0d3ea-a4d7-4e88-8f01-5aceb2d3c61b" : "checkin.xml",
"251c03fa-a9dc-4157-855f-b016f4fae9ab": "checkinMaternal.xml"
}
I will create a separate PR for the changes I had to make to the CustomAppLoaderFactory. Thanks!
=> SL-480: configure widget with multiple encounter types with different forms

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js
@mogoodrich , I got this widget working to display obs only from the current program enrollment if the duringCurrentEnrollmentInProgram config parameter is specified:
=> SL-734: add new duringCurrentEnrollmentInProgram config parameter to display obs only from the current program enrollment

omod/src/main/web/dashboardwidgets/obsgraph/obsgraph.controller.js
@mogoodrich , I finally figured out the problem with this widget, and why sometimes it did not show any data. The problem was that all the REST calls were executed asynchronously with no way of controlling the order of those REST calls. Therefore, sometimes the obs REST call was returning before the programenrollment, and the widget was configured to display only obs during a certain program enrollment but we had no enrollment date because the REST call did not return before the obs rest.
So, now I chained those REST calls to execute sequentially, the grapah loads correctly every time:
=> SL-734: sequentially chain the REST calls

omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/dashboardwidgets/DashboardWidgetFragmentController.java, omod/src/main/webapp/fragments/clinicianfacing/diagnosisWidget.gsp, omod/src/main/webapp/fragments/clinicianfacing/visitsSection.gsp, omod/src/main/webapp/fragments/dashboardwidgets/customLinksWidget.gsp, omod/src/main/webapp/fragments/dashboardwidgets/dashboardWidget.gsp, omod/src/main/webapp/fragments/patientdashboard/activeDrugOrders.gsp, omod/src/main/webapp/fragments/program/programHistory.gsp
Add html class names to various widgets. This makes is easier to select and hide them when embedding the O2 dashboard into an O3 workspace. This PR is similar to [coorespondingn PR](https://github.com/PIH/openmrs-module-pihcore/pull/542) in `openmrs-module-pihcore`.
The work is not exhaustive, but should be good enough for selectors. Unlike the widgets in `module-pihcore`, a lot of these widgets don't have `app` in the Fragment model, so I avoided adding `${app.id}` class to all widgets.
=> UHM-8241: add html classes to widgets
